# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: xenial
cache: packages
before_install:
  - echo "dash dash/sh boolean false" | sudo debconf-set-selections
  - sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
